// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9mp-d_fepxC2TbEw_wzg0wbhDzvL1shw',
    appId: '1:726677962993:web:9c045cd89ab4188f6be950',
    messagingSenderId: '726677962993',
    projectId: 'novtrainingproject',
    authDomain: 'novtrainingproject.firebaseapp.com',
    storageBucket: 'novtrainingproject.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-z8rFsgMgTM9lJle2PWwgoQs8JWdVXCs',
    appId: '1:726677962993:android:8a7e28db28cfa2d16be950',
    messagingSenderId: '726677962993',
    projectId: 'novtrainingproject',
    storageBucket: 'novtrainingproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEf51Pi1S7lS1nEGRv__jCy056NDQJeSw',
    appId: '1:726677962993:ios:8ac62bdf285b0fe86be950',
    messagingSenderId: '726677962993',
    projectId: 'novtrainingproject',
    storageBucket: 'novtrainingproject.firebasestorage.app',
    iosBundleId: 'com.androbim.novTrainingSession',
  );
}
