name: nov_training_session
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: 4.6.6
  freezed_annotation: 2.4.4
  json_annotation: 4.9.0
  shared_preferences: 2.3.4
  sqflite: 2.4.1
  path: 1.9.0
  path_provider: 2.1.5
  contacts_service: 0.6.3
  permission_handler: 11.3.1
  geolocator: 13.0.2
  google_maps_flutter: 2.10.0
  http: 1.2.2
  url_launcher: 6.3.1
  firebase_core: 3.10.1
  firebase_auth: 5.4.1
  google_sign_in: 6.1.2
  cloud_firestore: 5.6.2
  flutter_local_notifications: ^17.1.2
  firebase_messaging: ^15.2.0
  firebase_storage: 12.4.0
  image_picker: 1.1.2



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: 2.4.14
  freezed: 2.5.2
  json_serializable: 6.8.0



flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
